### PR TITLE
condor_submit command

### LINKED ISSUE #105: pycondor.Job: condor_submit command built/submitted incorrectly
#### Description
Bug in pycondor.Job submit_job method

#### Steps/code to reproduce issue

See below for an example trying to submit a basic job.

```
from pycondor import Job, Dagman
import os

os.environ['PYCONDOR_SUBMIT_DIR'] = os.path.abspath('condor\\submit')
os.environ['PYCONDOR_ERROR_DIR']  = os.path.abspath('condor\\error')
os.environ['PYCONDOR_LOG_DIR']    = os.path.abspath('condor\\log')
os.environ['PYCONDOR_OUTPUT_DIR'] = os.path.abspath('condor\\output')

exe = os.path.abspath('DummyExe.exe')

job = Job(
  name = 'job01',
  executable = exe,
)

job.add_arg(arg = 'arg01 arg02')

print('building...')
job.build()

print('submitting...')
job.submit_job()
```

#### Expected results

`building...
submitting...
Submitting job(s).
1 job(s) submitted to cluster 24.`

#### Actual results

`building...
submitting...
The filename, directory name, or volume label syntax is incorrect.`

### PR DESCRIPTION
**Pull request by karlhornlund**
#### Reference Issue
Fixes #105 

#### What does this pull request implement/fix? Explain your changes.
shlex.split() removes path separators in Windows, so isn't a suitable solution.

I propose:

```
command = ['condor_submit']
if submit_options is not None:
  for option in submit_options.split(' '):
    command.append(option)
command.append(self.submit_file)

proc = subprocess.Popen(command,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.PIPE)
out, err = proc.communicate()
```

### CODE REVIEW

**Comment by karlhornlund** [comment]
Seems to work.

I've added it as a function to utils so we can use it without repetition in `job.py` and `dagman.py` (and potentially elsewhere in the future), and I've added a test around it.

What do you think?

**Comment by jrbourbeau** [comment]
> I've added it as a function to utils so we can use it without repetition in job.py and dagman.py (and potentially elsewhere in the future), and I've added a test around it.

Wow, thanks so much!

**Comment by karlhornlund** [comment]
I'm new to this - has that fixed it?

**Comment by jrbourbeau** [comment]
Yep, everything looks good to me 👍 Thanks @karlhornlund!

**Pull request merged**
