### PR TITLE
Queue bug fix in pycondor.Job

### LINKED ISSUE #38: Queue parameter in pycondor.Job not added to submit file when built by dagman
When a pycondor.Job that includes the queue parameter is built by a dagman object, the resulting submit file for the job does not contain the input queue parameter.

We do get the desired behavior in this case, when just building the job:
```python
job = pycondor.Job('examplejob', 'examplejob.py',
                          error=error, output=output,
                          log=log, submit=submit, verbose=2,
                          queue=5)
job.build()
```

However, when the job is built by a dagman object, we do not get the desired behavior:

```python
job = pycondor.Job('examplejob', 'examplejob.py',
                          error=error, output=output,
                          log=log, submit=submit, verbose=2,
                          queue=5)
dagman = pycondor.Dagman('exampledagman', submit=submit, verbose=2)
dagman.add_job(job)
dagman.build()
```

It seems to be an issue with the dagman implementation.

### PR DESCRIPTION
**Pull request by mattmeehan**
#### Reference Issue

Fixes #38 

#### What does this pull request implement/fix? Explain your changes.

Fixes bug in pycondor.job where queue parameters was not being properly assigned if the job was created by a dagman.

### CODE REVIEW

**Comment by jrbourbeau** [comment]
Awesome, thanks so much for the fix! 

Could you also add an entry to the changelog (`pycondor/docs/changelog.rst`) and a regression test to make sure that this bug doesn't pop up again? I'd also be more than happy to help with these additions!

**Comment by mattmeehan** [comment]
Yes, I'm happy to do both. Would this be under the most recent version (0.1.4) in the changelog, or do I create a new entry (i.e. 0.1.5)?

**Comment by jrbourbeau** [comment]
For a regression test, adding something like the following to `pycondor/pycondor/tests/test_dagman.py` that checks if a submit file for a `Job` built in inside a `Dagman` and outside a `Dagman` are the same should be sufficient. 

```python 
import os
import filecmp


def test_job_dag_submit_file_same(tmpdir):
    # Test to check that the submit file for a Job with no arguments is the
    # same whether built from a Dagman or not. See issue #38.

    example_script = os.path.join('examples/savelist.py')

    submit_dir = str(tmpdir.mkdir('submit'))

    # Build Job object that will be build outside of a Dagman
    job_outside_dag = pycondor.Job('job_outside_dag', example_script,
                                   submit=submit_dir, queue=5)
    job_outside_dag.build(fancyname=False)

    # Build Job object that will be build inside of a Dagman
    job_inside_dag = pycondor.Job('job_inside_dag', example_script,
                                  submit=submit_dir, queue=5)
    dagman = pycondor.Dagman('exampledagman', submit=submit_dir)
    dagman.add_job(job_inside_dag)
    dagman.build(fancyname=False)

    # Check that the contents of the two Job submit files are the same
    assert filecmp.cmp(job_outside_dag.submit_file, job_inside_dag.submit_file,
                       shallow=False)
```

**Comment by jrbourbeau** [comment]
> Yes, I'm happy to do both. Would this be under the most recent version (0.1.4) in the changelog, or do I create a new entry (i.e. 0.1.5)?

Version 0.1.4 is already uploaded to [PyPI](https://pypi.python.org/pypi/PyCondor), so this will need a new entry for version  0.1.5.

**Comment by jrbourbeau** [comment]
This PR looks great :smiley:, thank you for your contribution @mattmeehan!

**Pull request merged**
